import { Roboto_Flex as Roboto } from 'next/font/google'
import '../assets/styles/globals.css'

const font = Roboto({
  subsets: ['latin'],
  variable: '--font-main',
  fallback: ['sans serif']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={`${font.variable}`}>{children}</body>
    </html>
  )
}
